### PR TITLE
Capacitor V3 Support

### LINKED ISSUE #46: Update this plugin for Capacitor 3
Capacitor 3 is being built and is already in [beta](https://capacitorjs.com/blog/announcing-capacitor-3-0-beta). In this new version the native plugins have been removed from the core and there are some changes that are necessary in the existing plugins.

**Example: Plugin Imports**
The Plugins object is deprecated, but will continue to work in Capacitor 3. Capacitor plugins should be updated to use the new plugin registration APIs (see the Upgrade Guide for plugins), which will allow them to be imported directly from the plugin’s package.

Going forward, the Plugins object from @capacitor/core should not be used.

```
// OLD
import { Plugins } from '@capacitor/core';
const { AnyPlugin } = Plugins;
Importing the plugin directly from the plugin’s package is preferred, but the plugin must be updated to work with Capacitor 3 for this to be possible.
```

```
// NEW
import { AnyPlugin } from 'any-plugin';
```

**References:**

[Updating Capacitor to 3.0 in your plugin](https://capacitorjs.com/docs/v3/updating/plugins/3-0)

[Updating Capacitor to 3.0 in your app](https://capacitorjs.com/docs/v3/updating/3-0)

### PR DESCRIPTION
**Pull request by thomasvidas**
This has breaking changes on the web side of how this plugin is imported

### CODE REVIEW

**Comment by enricodeleo** [comment]
Installed as `npm i @capacitor-community/firebase-analytics@next` I fund an error when building for Android (iOS is okay) on capacitor 3.

```
./app/node_modules/@capacitor-community/firebase-analytics/android/src/main/java/com/getcapacitor/community/firebaseanalytics/FirebaseAnalytics.java:41: error: cannot access AppCompatActivity
        bridge.getActivity()
                          ^
  class file for androidx.app
```

Any ideas?

**Comment by thomasvidas** [comment]
You may need to add AndroidX AppCompat to your app. This plugin does not include it so there is no version mismatch on Android. Check to see if your app's `build.gradle` has something like this. I believe the newest version is 1.2.0

```groovy
implementation 'androidx.appcompat:appcompat:1.x.x'
```

**Comment by kevinainleywalker** [comment]
I have the same issue as @enricodeleo .

AndroidX AppCompat is in my app.

from variables.gradle:

```
ext {
  minSdkVersion = 21
  compileSdkVersion = 30
  targetSdkVersion = 30
  androidxActivityVersion = '1.2.0'
  androidxAppCompatVersion = '1.2.0'
  androidxCoordinatorLayoutVersion = '1.1.0'
  androidxCoreVersion = '1.3.2'
  androidxFragmentVersion = '1.3.0'
  junitVersion = '4.13.1'
  androidxJunitVersion = '1.1.2'
  androidxEspressoCoreVersion = '3.3.0'
  cordovaAndroidVersion = '7.0.0'
}
```
From project build.gradle:

`implementation "androidx.appcompat:appcompat:$androidxAppCompatVersion"`

**Comment by enricodeleo** [comment]
@kevinainleywalker @thomasvidas same here

**Comment by crabbydavis** [comment]
Is this close to being finished and merged in?

**Comment by brownoxford** [comment]
@crabbydavis yes, pretty close. Tracking down a reported issue with browserify and then I'll probably merge this into master and create an LTS branch for capacitor v2.

**Comment by crabbydavis** [comment]
@brownoxford Awesome thanks!!

**Pull request merged**
